# Generated by Django 6.0 on 2025-12-09 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordentrabajo",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordenes_trabajo",
                to="core.planmantencion",
            ),
        ),
        migrations.AlterField(
            model_name="ordentrabajo",
            name="tecnico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordenes_trabajo",
                to="core.tecnico",
            ),
        ),
    ]
